### ISSUE TITLE
HTML body MIME part fails to set_content() if Content-Transfer-Encoding is not quoted-printable

### ISSUE THREAD

**Issue by zjt** [aws-samples/amazon-workmail-lambda-templates#17]
HTML body from Outlook:
`Content-Type: text/plain; charset="us-ascii"
Content-Transfer-Encoding: quoted-printable`

HTML body from WorkMail:
`Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable`

HTML body from Thunderbird:
`Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: 7bit`

The HTML message from Thunderbird results in:

`{"errorMessage": "'bytes' object has no attribute 'encode'", "errorType": "AttributeError", "stackTrace": ["  File \"/var/task/app.py\", line 98, in update_handler\n    updated_email = utils.update_email(downloaded_email, event['subject'], event['flowDirection'], key)\n", "  File \"/var/task/utils.py\", line 248, in update_email\n    updated_email = update_email_body(downloaded_email, key)\n", "  File \"/var/task/utils.py\", line 156, in update_email_body\n    part.set_content(new_html_body.encode(html_charset), \"text\", \"html\", cte=transfer_encoding)\n", "  File \"/var/lang/lib/python3.7/email/message.py\", line 1171, in set_content\n    super().set_content(*args, **kw)\n", "  File \"/var/lang/lib/python3.7/email/message.py\", line 1101, in set_content\n    content_manager.set_content(self, *args, **kw)\n", "  File \"/var/lang/lib/python3.7/email/contentmanager.py\", line 37, in set_content\n    handler(msg, obj, *args, **kw)\n", "  File \"/var/lang/lib/python3.7/email/contentmanager.py\", line 243, in set_bytes_content\n    data.encode('ascii')\n"]}`

**Comment by sagariiit** [comment]
I was able to reproduce this issue by sending an email via yahoo mail which also sends content-type `text/html` with `charset` UTF-8 and Content-Transfer-Encoding`7bit`.  Now here even though charset is set to UTF-8, since the encoding is 7-bit the html part can only send [U+0000 | U+007F] Unicode chars or else it can't be encoded in 7bit.

The issue arises after we amend the message with disclaimer/footer, [email.contentmanage](https://docs.python.org/3/library/email.contentmanager.html#email.contentmanager.raw_data_manager) does not like to set a UTF-8 content with 7bit encoding. 

As a fix, I am going to override the 7-bit encoding to quoted-printable when charset is set to UTF-8, this is more logical.
